# Generated by Django 3.1.1 on 2020-10-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201022_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecategory',
            name='slug',
            field=models.SlugField(allow_unicode=True, default=None, max_length=120, unique=True, verbose_name='آدرس دسته بندی'),
        ),
    ]
