# Generated by Django 3.1.1 on 2020-10-22 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_articlecategory_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlecategory',
            name='slug',
        ),
        migrations.AlterField(
            model_name='articlecategory',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='عنوان دسته بندی'),
        ),
    ]
